export const uiCopy = {
  common: {
    homeAria: 'EventPilot 首页',
    requestFailed: '请求失败，请稍后重试。',
    userFallback: 'EventPilot 用户',
  },
  navigation: {
    login: '登录',
    register: '注册',
    dashboard: '控制台',
    newTask: '新建任务',
    logout: '退出登录',
    openUserMenu: '打开用户菜单',
    toggleMenu: '打开或关闭菜单',
  },
  auth: {
    loginRequired: '请先登录后继续操作',
    checkingSession: '正在检查登录状态...',
    shell: {
      backHome: '返回首页',
      heading: '把活动规划放进更安静的工作区。',
      description:
        'EventPilot 会把任务创建、结构化生成和完整文档解锁串成清晰流程，让团队在需要时继续推进。',
      chips: ['策划草案', '复盘检查', '交接文档'],
    },
    login: {
      eyebrow: '欢迎回来',
      title: '登录 EventPilot',
      description: '登录后即可创建 AI 活动任务，并保持生成流程受保护。',
      emailLabel: '邮箱',
      emailPlaceholder: 'name@example.com',
      passwordLabel: '密码',
      passwordPlaceholder: '输入密码',
      submit: '登录',
      submitting: '正在登录',
      newUserPrefix: '还没有账号？',
      registerLink: '注册',
      fallbackError: '登录失败，请稍后重试。',
      validation: {
        emailRequired: '请输入邮箱。',
        emailInvalid: '请输入有效的邮箱地址。',
        passwordRequired: '请输入密码。',
      },
    },
    register: {
      eyebrow: '创建账号',
      title: '注册 EventPilot',
      description: '创建账号后，再开始生成你的 AI 活动文档。',
      usernameLabel: '用户名',
      usernamePlaceholder: '你的名字',
      emailLabel: '邮箱',
      emailPlaceholder: 'name@example.com',
      passwordLabel: '密码',
      passwordPlaceholder: '至少 6 个字符',
      confirmPasswordLabel: '确认密码',
      confirmPasswordPlaceholder: '再次输入密码',
      submit: '注册',
      submitting: '正在创建',
      existingUserPrefix: '已有账号？',
      loginLink: '登录',
      successMessage: '账号已创建，请登录后继续。',
      fallbackError: '注册失败，请稍后重试。',
      validation: {
        usernameRequired: '请输入用户名。',
        emailRequired: '请输入邮箱。',
        emailInvalid: '请输入有效的邮箱地址。',
        passwordTooShort: '密码至少需要 6 个字符。',
        passwordMismatch: '两次输入的密码不一致。',
      },
    },
  },
  dashboard: {
    title: '控制台',
    description: '集中查看活动任务、生成进度和交接文档。',
    newTask: '新建任务',
    recentTasks: '最近任务',
    workspace: '工作区',
    nav: {
      dashboard: '控制台',
      newTask: '新建任务',
      library: '任务库',
      settings: '设置',
      support: '支持',
    },
    sampleUser: {
      name: 'Maya Rivera',
      organization: '计算机协会',
    },
    stats: {
      activeTasks: '进行中的任务',
      inReview: '待复盘',
      completedThisTerm: '本学期已完成',
    },
    newTaskForm: {
      backToDashboard: '返回控制台',
      title: '新建任务',
      description: '描述你的活动，EventPilot 会生成一份可继续完善的草案。',
      modeLegend: '你需要什么？',
      eventNameLabel: '活动名称',
      eventNamePlaceholder: '例如：2026 春季联谊晚会',
      eventTypeLabel: '活动类型',
      eventTypePlaceholder: '选择类型',
      eventTypeOptions: {
        social: '社交 / 联谊',
        fundraiser: '筹款活动',
        conference: '会议 / 论坛',
        workshop: '工作坊',
        meeting: '例会',
      },
      targetDateLabel: '目标日期',
      attendeesLabel: '预计人数',
      budgetLabel: '预算（可选）',
      budgetPlaceholder: '例如：6500 元',
      goalsLabel: '目标与备注',
      goalsPlaceholder: '说明活动目标、限制条件、主题方向或其他重要要求...',
      cancel: '取消',
      generate: '生成',
      generating: '生成中…',
      taskTypes: [
        {
          value: 'pack',
          label: '活动策划包',
          desc: '时间线、预算、分工和清单',
        },
        {
          value: 'review',
          label: '文档复盘',
          desc: '标记遗漏、风险和规范问题',
        },
        {
          value: 'handoff',
          label: '交接文档',
          desc: '整理成便于分享和移交的摘要',
        },
      ],
    },
  },
  result: {
    backToDashboard: '返回控制台',
    generatedJustNow: '刚刚生成',
    share: '分享',
    export: '导出',
    metaLabels: {
      audience: '对象',
      date: '日期',
      venue: '地点',
      budget: '预算',
    },
    whatYouGet: '解锁后可获得',
    benefits: ['完整预算拆解', '角色与职责分工', '当天执行流程', '活动前检查清单', '可编辑导出（PDF / 文档）'],
    unlocked: '已解锁',
    locked: '未解锁',
    unlockHint: '输入兑换码解锁',
    redeem: {
      invalidCode: '兑换码无效，请检查后重试。',
      unlockedTitle: '完整内容已解锁',
      unlockedDescription: '现在可以查看、编辑和导出所有章节。',
      lockedTitle: '解锁完整文档',
      lockedDescription: '预算、分工、执行流程和检查清单仍处于锁定状态。',
      codeLabel: '兑换码',
      codePlaceholder: '输入兑换码',
      checking: '检查中…',
      submit: '解锁完整内容',
      noCode: '没有兑换码？',
      upgrade: '升级方案',
      demoCodePrefix: '演示可试用',
    },
  },
} as const
