export const uiCopy = {
  common: {
    homeAria: 'EventPilot 首页',
    requestFailed: '请求失败，请稍后重试。',
    userFallback: 'EventPilot 用户',
  },
  navigation: {
    login: '登录',
    register: '注册',
    dashboard: '控制台',
    newTask: '新建任务',
    logout: '退出登录',
    openUserMenu: '打开用户菜单',
    toggleMenu: '打开或关闭菜单',
    switchToLightTheme: '切换到浅色模式',
    switchToDarkTheme: '切换到深色模式',
  },
  auth: {
    loginRequired: '请先登录后继续操作',
    checkingSession: '正在检查登录状态...',
    shell: {
      backHome: '返回首页',
      heading: '把活动规划放进更安静的工作区。',
      description:
        'EventPilot 会把任务创建、结构化生成和完整文档解锁串成清晰流程，让团队在需要时继续推进。',
      chips: ['策划草案', '复盘检查', '交接文档'],
    },
    login: {
      eyebrow: '欢迎回来',
      title: '登录 EventPilot',
      description: '登录后即可创建 AI 活动任务，并保持生成流程受保护。',
      emailLabel: '邮箱',
      emailPlaceholder: 'name@example.com',
      passwordLabel: '密码',
      passwordPlaceholder: '输入密码',
      submit: '登录',
      submitting: '正在登录',
      newUserPrefix: '还没有账号？',
      registerLink: '注册',
      fallbackError: '登录失败，请稍后重试。',
      validation: {
        emailRequired: '请输入邮箱。',
        emailInvalid: '请输入有效的邮箱地址。',
        passwordRequired: '请输入密码。',
      },
    },
    register: {
      eyebrow: '创建账号',
      title: '注册 EventPilot',
      description: '创建账号后，再开始生成你的 AI 活动文档。',
      usernameLabel: '用户名',
      usernamePlaceholder: '你的名字',
      emailLabel: '邮箱',
      emailPlaceholder: 'name@example.com',
      passwordLabel: '密码',
      passwordPlaceholder: '至少 6 个字符',
      confirmPasswordLabel: '确认密码',
      confirmPasswordPlaceholder: '再次输入密码',
      submit: '注册',
      submitting: '正在创建',
      existingUserPrefix: '已有账号？',
      loginLink: '登录',
      successMessage: '账号已创建，请登录后继续。',
      fallbackError: '注册失败，请稍后重试。',
      validation: {
        usernameRequired: '请输入用户名。',
        emailRequired: '请输入邮箱。',
        emailInvalid: '请输入有效的邮箱地址。',
        passwordTooShort: '密码至少需要 6 个字符。',
        passwordMismatch: '两次输入的密码不一致。',
      },
    },
  },
  publicPages: {
    shell: {
      backHome: '返回首页',
    },
    taskCreate: {
      backHome: '返回首页',
      eyebrow: '创建活动任务',
      title: '把活动信息整理成可执行文档',
      description:
        '填写活动背景、规模和限制条件，EventPilot 会生成启动、复盘或交接所需的结构化内容。',
      modeLegend: '生成模式',
      formTitle: '活动基础信息',
      formDescription: '必填项越清晰，生成结果越接近真实执行场景。',
      requiredHint: '必填',
      modes: [
        {
          value: 'startup',
          label: '活动启动包',
          desc: '时间线、预算、分工、清单',
        },
        {
          value: 'review',
          label: '活动复盘包',
          desc: '数据整理、问题标记、改进建议',
        },
        {
          value: 'handoff',
          label: '换届交接包',
          desc: '流程文档、注意事项、一键移交',
        },
      ],
      activityTypes: [
        '社团活动',
        '讲座',
        '比赛',
        '工作坊',
        '展览',
        '招新',
        '志愿服务',
        '晚会',
        '路演',
        '其他',
      ],
      fields: {
        activityName: {
          label: '活动名称',
          placeholder: '例如：2026 春季社团文化节',
          requiredError: '活动名称不能为空',
        },
        organizationName: {
          label: '组织名称',
          placeholder: '例如：计算机协会',
          requiredError: '组织名称不能为空',
        },
        activityType: {
          label: '活动类型',
          placeholder: '选择活动类型',
        },
        expectedParticipants: {
          label: '预计人数',
          placeholder: '180',
        },
        dateOrPeriod: {
          label: '时间周期',
          placeholder: '例如：2026 年 4 月中旬 或 第 8-10 周',
        },
        location: {
          label: '地点',
          placeholder: '例如：多功能厅 / 线上',
        },
        budgetRange: {
          label: '预算范围',
          placeholder: '例如：3000-5000 元 或 待定',
        },
        targetAudience: {
          label: '面向对象',
          placeholder: '例如：全校学生 / 社团成员',
        },
        extraContext: {
          label: '其他背景',
          placeholder: '活动目标、主题方向、特殊需求，或其他你认为重要的背景信息。',
        },
        pastedMaterials: {
          label: '粘贴已有资料',
          placeholder: '已有策划草稿、会议记录、参考案例，可以直接粘贴到这里。',
        },
      },
      loading: {
        created: '任务已创建，正在打开结果页…',
        creating: '正在创建任务…',
        description: '系统会先保存任务，再进入后台生成流程。',
        waiting: '生成中，请稍候…',
        redirecting: '正在跳转…',
      },
      errors: {
        missingResultLink: '生成成功但未收到结果链接，请稍后重试。',
        network: '网络错误，请检查连接后重试。',
      },
      actions: {
        cancel: '取消',
        submit: '开始生成',
      },
      sidePanel: {
        title: '生成后你会得到',
        description: '首屏先展示预览内容，完整章节可通过兑换码解锁。',
        items: ['活动概览', '筹备时间线', '预算和物资', '人员分工', '当天流程', '检查清单'],
        workflowTitle: '工作流',
        workflow: ['填写活动信息', '生成结构化预览', '查看结果并解锁完整文档'],
      },
    },
    taskResult: {
      backCreate: '返回新建任务',
      back: '返回',
      generatedJustNow: '刚刚生成',
      demoBadge: '演示页面',
      copyMarkdown: '复制 Markdown',
      copied: '已复制',
      copyError: '复制失败，请手动选择文本复制。',
      typeLabel: '类型',
      allUnlockedTitle: '全部内容已解锁',
      allUnlockedDescription: '所有章节现在可以查看和复制。点击右上角「复制 Markdown」即可导出。',
      modeLabels: {
        startup: '活动启动包',
        review: '活动复盘包',
        handoff: '换届交接包',
      },
      metaLabels: {
        audience: '面向',
        date: '时间',
        venue: '场地',
        budget: '预算',
      },
      fallbackMeta: {
        unknown: '待确认',
        participantsPrefix: '约 ',
        participantsSuffix: ' 人',
      },
      lockedPlaceholderSections: [
        {
          id: 'timeline',
          title: '时间线 Checklist',
          summary: '筹备周期和各阶段里程碑。',
          items: ['解锁后查看完整时间线'],
        },
        {
          id: 'budget',
          title: '预算项目清单',
          summary: '按项目列出的预算明细。',
          items: ['解锁后查看预算明细'],
        },
        {
          id: 'roles',
          title: '人员分工建议',
          summary: '各岗位职责和备选联系人。',
          items: ['解锁后查看分工详情'],
        },
        {
          id: 'schedule',
          title: '活动当天流程',
          summary: '活动日按分钟排布的执行时间表。',
          items: ['解锁后查看当天流程'],
        },
        {
          id: 'checklist',
          title: '活动前 48 小时检查清单',
          summary: '最后确认事项，确保不遗漏。',
          items: ['解锁后查看检查清单'],
        },
      ],
      lockedDescriptions: [
        '时间线 Checklist、预算项目清单、人员分工建议',
        '活动当天流程、活动前 48 小时检查清单',
      ],
      sectionState: {
        unlocked: '已解锁',
        locked: '已锁定',
        unlockHint: '输入兑换码解锁',
      },
      state: {
        generatingTitle: '正在生成活动流程包…',
        generatingDescription: '通常需要 20-60 秒，请稍候。',
        loadingTitle: '正在加载结果…',
        loadingDescription: '正在读取任务状态和预览内容。',
        emptyTitle: '暂时没有可展示的内容',
        emptyDescription: '任务已创建，但还没有生成可展示章节。请稍后刷新页面。',
        failedGeneration: '生成失败，请返回重新提交或稍后重试。',
        notFound: '任务不存在或链接已失效',
        loadFailed: '加载失败，请稍后重试',
        fallbackFailed: '加载失败',
        untitledTask: '未命名活动',
      },
      demo: {
        title: '这是演示页面',
        description: '真实生成的活动任务需要输入兑换码才能解锁完整内容。',
        actionPrefix: '创建一个真实任务',
        actionSuffix: '，体验完整流程。',
      },
      demoResult: {
        title: '2026 春季社团文化节',
        type: '活动启动包',
        meta: {
          audience: '全校学生（约 180 人）',
          date: '2026 年 4 月中旬',
          venue: '学生活动中心多功能厅',
          budget: '3000-5000 元',
        },
        sections: [
          {
            id: 'overview',
            title: '活动概览',
            summary:
              '面向全校学生的社团文化展示活动，包含互动体验、成果展览和主题分享。',
            items: [
              '目标：展示计算机协会年度成果，吸引新成员，促进社团间交流',
              '主题：「科技与人文」',
              '形式：14:00 互动展区开放，15:30 主题分享，17:00 自由交流',
            ],
          },
          {
            id: 'timeline',
            title: '时间线 Checklist',
            summary: '八周筹备周期，按周拆分里程碑和负责人。',
            items: [
              '第 8 周：确认场地预定和押金',
              '第 6 周：确定参展社团名单和整体活动流程',
              '第 4 周：启动线上线下宣传、开放报名',
              '第 2 周：确认物资清单、设备和志愿者排班',
            ],
          },
          {
            id: 'budget',
            title: '预算项目清单',
            summary: '按项目列出预算明细，含缓冲金。',
            items: [
              '场地及设备租赁：1200 元',
              '宣传物料（海报、横幅、传单）：600 元',
              '茶歇及活动物料：800 元',
              '应急预留（约 10%）：400 元',
            ],
          },
          {
            id: 'roles',
            title: '人员分工建议',
            summary: '明确各岗位职责和备选联系人。',
            items: [
              '活动总负责人：统筹协调、对外联络、进度追踪',
              '宣传组：海报设计、推文撰写、线上线下推广',
              '物资组：物料采购、现场布置、设备调试',
              '接待组：签到引导、嘉宾接待、现场秩序维护',
            ],
          },
          {
            id: 'schedule',
            title: '活动当天流程',
            summary: '活动日按分钟排布的执行时间表。',
            items: [
              '12:00 布置组到场，摆放展架、调试设备',
              '13:30 设备联调完成，签到台就位',
              '14:00 互动展区开放，观众入场',
              '15:30 主题分享环节开始',
              '17:00 自由交流、合影、发放纪念品',
              '17:30 撤场，物资清点归位',
            ],
          },
          {
            id: 'checklist',
            title: '活动前 48 小时检查清单',
            summary: '最后 48 小时的确认清单，确保不遗漏。',
            items: [
              '与场地管理方确认使用时间和注意事项',
              '打印签到表、活动流程单和紧急联系人表',
              '检查投影、音响、话筒等设备是否正常',
              '向志愿者逐一确认到岗时间和分工',
              '准备应急物资包（备用转接头、打印纸、充电宝、胶带）',
            ],
          },
        ],
      },
      redeem: {
        unlockedTitle: '解锁后可获得',
        exportHint: '点击右上角「复制 Markdown」可导出完整文档。',
        title: '解锁完整内容',
        description: '预算、分工、流程表和检查清单需要解锁。',
        codeLabel: '兑换码',
        codePlaceholder: '输入兑换码',
        invalidCode: '兑换码无效，请检查后重试。',
        usedCode: '该兑换码已被使用。',
        failed: '解锁失败，请稍后重试',
        checking: '验证中…',
        submit: '解锁',
        noCode: '还没有兑换码？',
        upgrade: '了解升级方案',
      },
    },
  },
  dashboard: {
    title: '控制台',
    description: '集中查看活动任务、生成进度和交接文档。',
    newTask: '新建任务',
    recentTasks: '最近任务',
    workspace: '工作区',
    nav: {
      dashboard: '控制台',
      newTask: '新建任务',
      library: '任务库',
      settings: '设置',
      support: '支持',
    },
    sampleUser: {
      name: 'Maya Rivera',
      organization: '计算机协会',
    },
    stats: {
      activeTasks: '进行中的任务',
      inReview: '待复盘',
      completedThisTerm: '本学期已完成',
    },
    newTaskForm: {
      backToDashboard: '返回控制台',
      title: '新建任务',
      description: '描述你的活动，EventPilot 会生成一份可继续完善的草案。',
      modeLegend: '你需要什么？',
      eventNameLabel: '活动名称',
      eventNamePlaceholder: '例如：2026 春季联谊晚会',
      eventTypeLabel: '活动类型',
      eventTypePlaceholder: '选择类型',
      eventTypeOptions: {
        social: '社交 / 联谊',
        fundraiser: '筹款活动',
        conference: '会议 / 论坛',
        workshop: '工作坊',
        meeting: '例会',
      },
      targetDateLabel: '目标日期',
      attendeesLabel: '预计人数',
      budgetLabel: '预算（可选）',
      budgetPlaceholder: '例如：6500 元',
      goalsLabel: '目标与备注',
      goalsPlaceholder: '说明活动目标、限制条件、主题方向或其他重要要求...',
      cancel: '取消',
      generate: '生成',
      generating: '生成中…',
      taskTypes: [
        {
          value: 'pack',
          label: '活动策划包',
          desc: '时间线、预算、分工和清单',
        },
        {
          value: 'review',
          label: '文档复盘',
          desc: '标记遗漏、风险和规范问题',
        },
        {
          value: 'handoff',
          label: '交接文档',
          desc: '整理成便于分享和移交的摘要',
        },
      ],
    },
  },
  result: {
    backToDashboard: '返回控制台',
    generatedJustNow: '刚刚生成',
    share: '分享',
    export: '导出',
    metaLabels: {
      audience: '对象',
      date: '日期',
      venue: '地点',
      budget: '预算',
    },
    whatYouGet: '解锁后可获得',
    benefits: ['完整预算拆解', '角色与职责分工', '当天执行流程', '活动前检查清单', '可编辑导出（PDF / 文档）'],
    unlocked: '已解锁',
    locked: '未解锁',
    unlockHint: '输入兑换码解锁',
    redeem: {
      invalidCode: '兑换码无效，请检查后重试。',
      unlockedTitle: '完整内容已解锁',
      unlockedDescription: '现在可以查看、编辑和导出所有章节。',
      lockedTitle: '解锁完整文档',
      lockedDescription: '预算、分工、执行流程和检查清单仍处于锁定状态。',
      codeLabel: '兑换码',
      codePlaceholder: '输入兑换码',
      checking: '检查中…',
      submit: '解锁完整内容',
      noCode: '没有兑换码？',
      upgrade: '升级方案',
      demoCodePrefix: '演示可试用',
    },
  },
} as const
